project: 
  type: book

book:
  sidebar:
    style: "floating"
    collapse-level: 1
  title: "Arvuti kasutamine uurimistöös"
  subtitle: "Informaatika valikaine e-õpik gümnaasiumile"
  author: "Mart Laanpere, Katrin Niglas, Kairi Osula, Kai Pata"
  date: "07/01/2013"
  chapters:
    - "index.qmd"
    - "peatukk1/peatukk1.qmd"
    - "peatukk2/peatukk2.qmd"
    - "peatukk3/peatukk3.qmd"
    - "peatukk4/peatukk4.qmd"
    - "peatukk5/peatukk5.qmd"
    - "kokkuvotte.qmd"
    - "viited.qmd"

bibliography: "references.bib"

format:
  html:
    theme:
      - "cosmo"
      - "brand"
    css: 
    - "components.css"
  pdf:
    documentclass: "scrreprt"



